
# Create ProductTypeAttribute
POST http://localhost/api/product-types/attributes HTTP/1.1
content-type: application/json

{
    "name": "Att102",
    "type": "Text", 
    "attributeValue":"This is me"
}

###
#Get ProductTypeAttributes
GET http://localhost/api/product-types/attributes HTTP/1.1


### Create ProductType
POST http://localhost/api/product-types HTTP/1.1
content-type: application/json

{
    "name": "Type101",
    "attributes":[2,4]
}

### Get product types
GET http://localhost/api/product-types HTTP/1.1