
# Create ProductTypeAttribute
POST http://localhost/api/product-types/attributes HTTP/1.1
content-type: application/json

{
    "name": "Attooof",
    "type": "Boolean", 
    "attributeValue":false
}

###
#Get ProductTypeAttributes
GET http://localhost/api/product-types/attributes HTTP/1.1


### Create ProductType
POST http://localhost/api/product-types HTTP/1.1
content-type: application/json

{
    "name": "Type103",
    "attributes":[1,2]
}

### Get product types
GET http://localhost/api/product-types HTTP/1.1


### Get ALL products
GET http://localhost/api/products HTTP/1.1

### Create Product
POST http://localhost/api/products HTTP/1.1
content-type: application/json

{
    "name": "Product0122",
    "productType_id":3,
    "assignedAttributes": [1,2]
}