
# Create ProductTypeAttribute
POST http://localhost/api/product-types/attributes HTTP/1.1
content-type: application/json

{
    "name": "Attooof101",
    "type": "Text", 
    "attributeValue":"hello"
}

###
#Get ProductTypeAttributes
GET http://localhost/api/product-types/attributes HTTP/1.1


### Create ProductType
POST http://localhost/api/product-types HTTP/1.1
content-type: application/json

{
    "name": "Type101",
    "attributes":[1]
}

### Get product types
GET http://localhost/api/product-types HTTP/1.1


### Get ALL products
GET http://localhost/api/products HTTP/1.1

### Create Product
POST http://localhost/api/products HTTP/1.1
content-type: application/json

{
    "name": "Product02",
    "productType_id":2,
    "assignedAttributes": [1]
}