version: '3.8'
services:
  nginx:
    image: nginx:stable-alpine
    depends_on:
      - api
      - web
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      
  api:
    image: mrp_api:1.0.0-dev
    build:
      dockerfile: Dockerfile
      context: ./api/.
      # will build only the development stage 
      target: development
    volumes:
      - ./api:/app
      - ./app/node_modules
    command: yarn start:migrate:dev
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/mrp_db_dev?schema=public"
      NODE_ENV: development
      PORT: 3001
    ports:
      - 3001:3001
  
  web:
    image: mrp_web:1.0.0-dev
    build:
      dockerfile: Dockerfile
      context: ./web/.
      # will build only the development stage 
      target: development
    volumes:
      - ./web:/app
      - ./app/node_modules
    command: yarn dev

    depends_on:
      - api
    environment:
      PORT: 3000
    ports:
      - 3000:3000
  
  postgres:
    image: postgres:12.10-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: mrp_db_dev
    volumes:
      - database:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: kfekairi@digitrans.link
      PGADMIN_DEFAULT_PASSWORD: 441257
    depends_on:
      - postgres
    ports:
      - "5050:80"
volumes:
  database:
