version: '3.8'
services:
  nginx:
    image: nginx:stable-alpine
    depends_on:
      - api
      - web
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
  
  api:
    image: releasin_api:1.0.0
    build:
      dockerfile: Dockerfile
      context: ./api/.
    volumes:
      - ./app/node_modules
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/releasin_db?schema=public"
      PORT: 3001
    ports:
      - 3001:3001
  
  web:
    image: releasin_web:1.0.0
    build:
      dockerfile: Dockerfile
      context: ./web/.
    volumes:
      - ./app/node_modules
    depends_on:
      - api
    environment:
      PORT: 3000
    ports:
      - 3000:3000

  postgres:
    image: postgres:12.10-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: releasin_db
    volumes:
      - database:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@digitrans.link
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - postgres
    ports:
      - "5050:80"
    volumes:
      - pgadmin:/var/lib/pgadmin
volumes:
  database:
  pgadmin:
